const endpoint=(base,path)=>new URL(path,base).toString();
const jsonHeaders={accept:"application/json","content-type":"application/json"};
const pageNumber=(items,size,current)=>Array.isArray(items)&&items.length===size?{page:current+1}:null;
export const platformRequests={
  workday:(base,{tenant,listingPath,offset=0,limit=20,pageSize,query="",location=""}={})=>{if(!tenant&&!listingPath)throw Error("incomplete: Workday source requires tenant or listingPath");const size=pageSize||limit;return{url:endpoint(base,listingPath||`/wday/cxs/${encodeURIComponent(tenant)}/jobs`),method:"POST",headers:jsonHeaders,body:{limit:size,offset,searchText:query,locations:location?[location]:[]},next:r=>Array.isArray(r.jobPostings)&&r.jobPostings.length===size?{offset:offset+size}:null}},
  eightfold:(base,{listingPath="/api/jobs",page=0,pageSize=20,cursor,query=""}={})=>{const url=new URL(listingPath,base);url.searchParams.set("query",query);url.searchParams.set("page",String(page));url.searchParams.set("pageSize",String(pageSize));if(cursor)url.searchParams.set("cursor",cursor);return{url:url.toString(),method:"GET",headers:{accept:"application/json"},next:r=>r.nextCursor||r.data?.nextCursor?{cursor:r.nextCursor||r.data.nextCursor,page:page+1}:pageNumber(r.positions||r.data?.positions,pageSize,page)}},
  icims:(base,{listingPath="/jobs/search",page=1,pageSize=20,query=""}={})=>{const url=new URL(listingPath,base);url.searchParams.set("search",query);url.searchParams.set("page",String(page));url.searchParams.set("pageSize",String(pageSize));return{url:url.toString(),method:"GET",headers:{accept:"application/json"},next:r=>pageNumber(r.jobs||r.searchResults,pageSize,page)}},
  "talentbrew-jibe":(base,{listingPath="/jobs",page=1,pageSize=20,query=""}={})=>{const url=new URL(listingPath,base);url.searchParams.set("keyword",query);url.searchParams.set("page",String(page));url.searchParams.set("size",String(pageSize));return{url:url.toString(),method:"GET",headers:{accept:"application/json"},next:r=>pageNumber(r.jobs||r.searchResults,pageSize,page)}},
  phenom:(base,{listingPath="/search-jobs",page=0,pageSize=20,query=""}={})=>{const url=new URL(listingPath,base);url.searchParams.set("keyword",query);url.searchParams.set("page",String(page));url.searchParams.set("limit",String(pageSize));return{url:url.toString(),method:"GET",headers:{accept:"application/json"},next:r=>pageNumber(r.jobs||r.data?.jobs,pageSize,page)}}
};
export function requestFor(adapter,base,config){const build=platformRequests[adapter];if(!build)throw Error(`unsupported adapter request: ${adapter}`);return build(base,config)};
