import assert from "node:assert/strict";import {createServer}from "node:http";import {spawn}from "node:child_process";import {after,before,test}from "node:test";import {listingHash}from "./worker.mjs";
let server,base;const seen=[];
before(async()=>{server=createServer(async(req,res)=>{let body="";for await(const part of req)body+=part;seen.push({url:req.url,method:req.method,token:req.headers["x-apple-csrf-token"],body});if(req.url==="/api/v1/CSRFToken"){res.setHeader("x-apple-csrf-token","fixture-token");return res.end("")}if(req.url==="/api/v1/search"){res.setHeader("content-type","application/json");return res.end(JSON.stringify({res:{totalRecords:2,searchResults:[{positionId:"2001",postingTitle:"Silicon Validation Engineer",transformedPostingTitle:"silicon-validation-engineer",locations:[{name:"Lisbon, Portugal"}],postDateInGMT:"2026-08-29",jobSummary:"Validate Apple silicon."},{positionId:"2002",postingTitle:"GPU Design Engineer",transformedPostingTitle:"gpu-design-engineer",locations:"Porto, Portugal",postDateInGMT:"2026-08-28",jobSummary:"Design Apple GPUs."}]}}))}res.statusCode=404;res.end()});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));base=`http://127.0.0.1:${server.address().port}`});
after(()=>new Promise(resolve=>server.close(resolve)));
const run=()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,["sidecar/worker.mjs"],{cwd:process.cwd()}),lines=[];child.stdout.on("data",data=>lines.push(...String(data).trim().split("\n").filter(Boolean)));child.on("error",reject);child.on("close",code=>code?reject(Error(`worker ${code}`)):resolve(lines.map(JSON.parse)));child.stdin.end(JSON.stringify({protocolVersion:1,command:"test_source",runId:"apple",source:{name:"Apple",baseUrl:`${base}/pt-pt/search?location=`,adapterId:"apple",kind:"active",allowPrivateNetwork:true,robotsOverride:true,configJson:{testNoDelay:true,locale:"pt-pt",maxPages:3}}})+"\n")});
test("Apple adapter uses CSRF search API and emits vacancies, not navigation links",async()=>{const events=await run(),jobs=events.filter(event=>event.event==="job").map(event=>event.payload),completed=events.at(-1);assert.equal(completed.event,"completed",JSON.stringify(events));assert.equal(completed.payload.mode,"direct-apple");assert.equal(completed.payload.discovered,2);assert.equal(jobs.length,2);assert.equal(jobs[0].title,"Silicon Validation Engineer");assert.equal(jobs[0].location,"Lisbon, Portugal");assert.equal(jobs[0].postedAt,"2026-08-29");assert.equal(jobs[0].canonicalUrl,`${base}/pt-pt/details/2001/silicon-validation-engineer`);const search=seen.find(request=>request.url==="/api/v1/search");assert.equal(search.method,"POST");assert.equal(search.token,"fixture-token");assert.equal(JSON.parse(search.body).locale,"pt-pt");assert.ok(!jobs.some(job=>["Overview","Locations","Benefits"].includes(job.title)))});

test("Apple warm check derives freshness from known listing hashes",async()=>{
 const known=[
  listingHash(`${base}/pt-pt/details/2001/silicon-validation-engineer`,"Silicon Validation Engineer",[{name:"Lisbon, Portugal"}]),
  listingHash(`${base}/pt-pt/details/2002/gpu-design-engineer`,"GPU Design Engineer","Porto, Portugal"),
 ];
 const events=await new Promise((resolve,reject)=>{const child=spawn(process.execPath,["sidecar/worker.mjs"],{cwd:process.cwd()}),lines=[];child.stdout.on("data",data=>lines.push(...String(data).trim().split("\n").filter(Boolean)));child.on("error",reject);child.on("close",code=>code?reject(Error(`worker ${code}`)):resolve(lines.map(JSON.parse)));child.stdin.end(JSON.stringify({protocolVersion:1,command:"check_source",runId:"apple-warm",known,source:{name:"Apple",baseUrl:`${base}/pt-pt/search?location=`,adapterId:"apple",kind:"active",allowPrivateNetwork:true,robotsOverride:true,configJson:{testNoDelay:true,locale:"pt-pt",maxPages:3}}})+"\n")});
 const completed=events.at(-1);
 assert.equal(completed.event,"completed");
 assert.equal(completed.payload.fresh,0);
 assert.equal(completed.payload.boardTotal,2);
 assert.equal(completed.payload.boardTotalExact,true);
});
