import assert from "node:assert/strict";import {createServer}from "node:http";import {spawn}from "node:child_process";import {test,before,after}from "node:test";
let server,base;
before(async()=>{server=createServer((req,res)=>{if(req.url==="/robots.txt")return res.end("User-agent: *\nAllow: /\n");if(req.url==="/blocked/robots.txt")return res.end("User-agent: *\nDisallow: /blocked\n");if(req.url==="/static")return res.end('<article class="job"><h2>Firmware Engineer</h2><a href="/apply">Apply</a></article>');if(req.url==="/xpath")return res.end('<article class="job"><h2>XPath Engineer</h2><a href="/apply">Apply</a></article>');if(req.url==="/page1")return res.end('<article class="job"><h2>Page One</h2></article><a class="next" href="/page2">Next</a>');if(req.url==="/page2")return res.end('<article class="job"><h2>Page Two</h2></article>');if(req.url==="/json")return res.setHeader("content-type","application/json").end(JSON.stringify({jobs:[{id:"j1",title:"Systems Engineer",company:"Example"}]}));if(req.url==="/workday")return res.setHeader("content-type","application/json").end(JSON.stringify({jobPostings:[{jobReqId:"wd1",title:"Workday Engineer",externalPath:"/wd"}]}));if(req.url==="/rss")return res.setHeader("content-type","application/rss+xml").end('<rss><channel><item><guid>r1</guid><title>Embedded Engineer</title><link>https://example.test/apply</link><description>Rust</description></item></channel></rss>');res.writeHead(429,{"retry-after":"1"}).end("slow down")});await new Promise(r=>server.listen(0,"127.0.0.1",r));base=`http://127.0.0.1:${server.address().port}`});after(()=>new Promise(r=>server.close(r)));
function run(path,configJson={},adapterId="static-css",extra={}){return new Promise((resolve,reject)=>{const c=spawn(process.execPath,["sidecar/worker.mjs"],{cwd:process.cwd()}),out=[];let err="";c.stdout.on("data",d=>out.push(...String(d).trim().split("\n").filter(Boolean)));c.stderr.on("data",d=>err+=d);c.on("error",reject);c.on("close",code=>code?reject(Error(err)):resolve(out.map(JSON.parse)));c.stdin.end(JSON.stringify({protocolVersion:1,command:"test_source",runId:"test",source:{name:"Fixture",baseUrl:base+path,adapterId,kind:"active",allowPrivateNetwork:true,configJson:{testNoDelay:true,...configJson},...extra}})+"\n")})}
const event=(events,name)=>events.find(e=>e.event===name);
test("CSS and XPath mappings emit normalized jobs",async()=>{const css=await run("/static",{itemSelector:".job",titleSelector:"h2",urlSelector:"a[href]"}),xpath=await run("/xpath",{itemXPath:"//article[@class='job']",titleXPath:"//h2",urlXPath:"//a"},"static-xpath");assert.equal(event(css,"job").payload.title,"Firmware Engineer");assert.equal(event(xpath,"job")?.payload.title,"XPath Engineer",JSON.stringify(xpath))});
test("preview reports mode, timing, and missing selector warnings without persistence",async()=>{const preview=await run("/static",{},"static-css"),final=preview.at(-1);assert.equal(final.payload.persisted,0);assert.equal(final.payload.mode,"direct");assert.equal(typeof final.payload.timingMs,"number");assert.match(final.payload.warnings.join(" "),/itemSelector/)});
test("JSON, RSS, and platform direct adapters parse deterministic shapes",async()=>{const json=await run("/json",{mode:"json"},"json"),rss=await run("/rss",{mode:"rss"},"rss"),wd=await run("/workday",{},"workday");assert.equal(event(json,"job").payload.company,"Example");assert.equal(event(rss,"job").payload.title,"Embedded Engineer");assert.equal(event(wd,"job").payload.externalId,"wd1")});
test("next-link pagination declares complete traversal",async()=>{const x=await run("/page1",{itemSelector:".job",titleSelector:"h2",nextSelector:".next"});assert.equal(x.filter(e=>e.event==="job").length,2);assert.equal(x.at(-1).payload.complete,true);assert.equal(x.at(-1).payload.pages,2)});
test("robots and rate limits are explicit failures, never empty success",async()=>{const blocked=await run("/blocked/jobs",{robotsUrl:base+"/blocked/robots.txt"}),limited=await run("/rate-limited",{});assert.equal(blocked.at(-1).payload.code,"robots_denied");assert.equal(limited.at(-1).payload.code,"rate_limited")});
test("override warning and unsupported custom sources are explicit",async()=>{const override=await run("/static",{itemSelector:".job",titleSelector:"h2"},"static-css",{robotsOverride:true}),custom=await run("/static",{},"custom-api");assert.equal(event(override,"warning").payload.code,"robots_override");assert.equal(custom.at(-1).payload.code,"incomplete")});
test("private targets and non HTTP schemes fail before worker navigation",async()=>{const privateTarget=await run("/static",{},"static-css",{allowPrivateNetwork:false}),badScheme=await run("/static",{urlTemplate:"file:///etc/passwd"});assert.equal(privateTarget.at(-1).payload.code,"network_error");assert.equal(badScheme.at(-1).payload.code,"network_error")});
