#!/usr/bin/env node
import readline from "node:readline";import {createHash}from "node:crypto";import {existsSync}from "node:fs";import {readFile}from "node:fs/promises";import {lookup} from "node:dns/promises";import net from "node:net";import {requestFor} from "./adapters.mjs";
const V=1,R=2,emit=(event,runId,payload={})=>process.stdout.write(`${JSON.stringify({protocolVersion:V,event,runId,payload})}\n`),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const edge=[process.env.ProgramFiles&&`${process.env.ProgramFiles}/Microsoft/Edge/Application/msedge.exe`,process.env["ProgramFiles(x86)"]&&`${process.env["ProgramFiles(x86)"]}/Microsoft/Edge/Application/msedge.exe`].filter(Boolean),privateHost=h=>h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||h==="::1";
export const adapters={"static-css":{version:"1.1.0",capabilities:["direct","css","pagination"]},"static-xpath":{version:"1.1.0",capabilities:["direct","xpath","pagination"]},json:{version:"1.1.0",capabilities:["direct","pagination"]},rss:{version:"1.1.0",capabilities:["direct"]},playwright:{version:"1.1.0",capabilities:["browser","headed","session"]},workday:{version:"1.1.0",capabilities:["direct-json","pagination","detail","playwright-fallback"]},eightfold:{version:"1.1.0",capabilities:["direct-json","cursor","detail","playwright-fallback"]},icims:{version:"1.1.0",capabilities:["direct-json","pagination","detail","playwright-fallback"]},"talentbrew-jibe":{version:"1.1.0",capabilities:["direct-json","pagination","detail","playwright-fallback"]},phenom:{version:"1.1.0",capabilities:["direct-json","pagination","detail","playwright-fallback"]},"custom-api":{version:"1.1.0",capabilities:[],unsupported:true},reference:{version:"1.1.0",capabilities:[],unsupported:true}};
export const privateAddress=ip=>{const v=net.isIP(ip);if(!v)return true;if(v===4)return /^(0\.|10\.|127\.|169\.254\.|192\.0\.(0|2)\.|192\.168\.|198\.(18|19|51\.100)\.|203\.0\.113\.|224\.|23\d\.|24\d\.|25[0-5]\.|172\.(1[6-9]|2\d|3[01])\.)/.test(ip);const x=ip.toLowerCase().replace(/^::ffff:/,"");if(net.isIP(x)===4)return privateAddress(x);return x==="::1"||x==="::"||x.startsWith("fe80:")||x.startsWith("fc")||x.startsWith("fd")||x.startsWith("ff");};
export const makeUrlGuard=(resolver=lookup)=>async(raw,s)=>{const u=new URL(raw);if(!["http:","https:"].includes(u.protocol))throw Error("network_error: only HTTP(S) URLs are allowed");if(s.allowPrivateNetwork)return u;const host=u.hostname.replace(/^\[|\]$/g,"");if(privateHost(host)||(net.isIP(host)&&privateAddress(host)))throw Error("network_error: private network target blocked");let addresses;try{addresses=await resolver(host,{all:true,verbatim:true})}catch{throw Error("network_error: DNS lookup failed")};if(!addresses.length||addresses.some(a=>privateAddress(a.address)))throw Error("network_error: resolved private/reserved address blocked");return u};
export const allowed=makeUrlGuard();
export const retryAfterMs=(header,nowMs=Date.now(),cap=30_000)=>{if(!header)return 0;const seconds=Number(header);const raw=Number.isFinite(seconds)?Math.ceil(seconds*1000):Math.max(0,Date.parse(header)-nowMs);return Math.min(cap,Math.max(0,raw||0))};
export const jitterMs=(random=Math.random)=>1500+Math.floor(random()*1501);
const urlFor=s=>String(s.configJson?.urlTemplate||s.baseUrl).replaceAll("{query}",encodeURIComponent(s.configJson?.query||"")).replaceAll("%QUERY%",encodeURIComponent(s.configJson?.query||""));
const num=v=>{const n=Number(v);return v!=null&&v!==""&&Number.isFinite(n)?n:null};
// ponytail: structured compensation fields only (salaryMin/Max/currency/period from ATS JSON); no
// free-text "$120k-$150k DOE" parser here — add one if a source only ever exposes salary as prose.
function job(x,s){const title=String(x.title||x.name||x.jobTitle||"").trim(),company=String(x.company||x.companyName||s.name||"").trim(),url=x.applyUrl||x.url||x.canonicalUrl||s.baseUrl,descriptionText=String(x.descriptionText||x.description||x.summary||x.jobDescription||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim(),externalId=x.externalId||x.id||x.requisitionId||x.jobReqId||x.jobId||createHash("sha256").update(`${s.baseUrl}|${title}|${company}|${url}`).digest("hex"),comp=x.compensation||x.payRange||x.salary||{},salaryMin=num(x.salaryMin??x.minSalary??x.payRangeMinimum??comp.min??comp.minimum),salaryMax=num(x.salaryMax??x.maxSalary??x.payRangeMaximum??comp.max??comp.maximum);return{externalId:String(externalId),canonicalUrl:String(x.canonicalUrl||url),applyUrl:String(x.applyUrl||url),title,company,location:x.location||x.locationName||null,workMode:x.workMode||null,descriptionText,descriptionHtml:String(x.descriptionHtml||x.description||"").slice(0,250000),postedAt:x.postedAt||x.postedDate||null,closingAt:x.closingAt||null,skills:Array.isArray(x.skills)?x.skills.map(String):[],seniority:x.seniority||x.seniorityLevel||x.jobLevel||null,salaryMin,salaryMax,salaryCurrency:x.salaryCurrency||x.currency||comp.currency||null,salaryPeriod:x.salaryPeriod||x.payPeriod||comp.period||null,salaryConfidence:salaryMin!=null||salaryMax!=null?"structured":null,adapterVersion:adapters[s.adapterId]?.version||"1.0.0",contentHash:createHash("sha256").update(`${title}\n${company}\n${descriptionText}`).digest("hex"),provenance:{adapter:s.adapterId,adapterVersion:adapters[s.adapterId]?.version||"1.0.0",sourceUrl:s.baseUrl}}}
const jitter=s=>s.configJson?.testJitterMs??jitterMs(s.configJson?.random||Math.random);
const cancelled=new Set;
const cancelledError=runId=>{if(cancelled.has(runId))throw Error("cancelled")};
async function wait(ms,s){cancelledError(s.__runId);await sleep(ms);cancelledError(s.__runId)}
async function get(url,s,redirects=0,request={}){let last;for(let i=0;i<=R;i++)try{cancelledError(s.__runId);const safe=await allowed(url,s);if(!s.configJson?.testNoDelay)await wait(jitter(s),s);const headers={"user-agent":"JobScraper/1.0 local personal use",...(s.__requestHeaders||{}),...(request.headers||{})},r=await fetch(safe,{redirect:"manual",method:request.method||"GET",headers,body:request.body===undefined?undefined:JSON.stringify(request.body),signal:AbortSignal.timeout(30000)});if([301,302,303,307,308].includes(r.status)){if(redirects>=10)throw Error("network_error: too many redirects");const next=r.headers.get("location");if(!next)throw Error("network_error: redirect missing location");return get(new URL(next,safe).toString(),s,redirects+1,{headers:request.headers})}if([401,403].includes(r.status))throw Error("auth_required");if(r.status===429){if(i===R)throw Error(`rate_limited retry-after=${r.headers.get("retry-after")||"unknown"}`);await wait(retryAfterMs(r.headers.get("retry-after"),Date.now(),30_000)||500*(i+1),s);continue}if(!r.ok){if(r.status>=500&&i<R){await wait(500*(i+1),s);continue}throw Error(`network_error HTTP ${r.status}`)}return{text:await r.text(),type:r.headers.get("content-type")||"",url:safe.toString()}}catch(e){last=e;if(/^(auth_required|rate_limited|robots_denied|cancelled)/.test(String(e.message||e))||i===R)throw e;await wait(500*(i+1),s)}throw last}
async function robots(s){if(s.robotsOverride){emit("warning",s.__runId,{code:"robots_override",message:"Saved per-source robots override is active."});return}const u=await allowed(urlFor(s),s);let r;try{r=await get(s.configJson?.robotsUrl||`${u.protocol}//${u.host}/robots.txt`,s)}catch(e){if(String(e.message||e).includes("HTTP 404"))return;throw e}let active=false;for(const line of r.text.split(/\r?\n/)){const[n,...rest]=line.split(":"),v=rest.join(":").trim();if(n.toLowerCase()==="user-agent")active=v==="*"||/jobscraper/i.test(v);if(active&&n.toLowerCase()==="disallow"&&v&&u.pathname.startsWith(v))throw Error("robots_denied")}}
const path=(v,p)=>p.split(".").filter(Boolean).reduce((x,k)=>x?.[k],v);
function collection(data,s){const a=s.adapterId,c=a==="workday"?data.jobPostings:a==="eightfold"?data.positions||data.data?.positions:a==="icims"||a==="talentbrew-jibe"?data.jobs||data.searchResults:a==="phenom"?data.jobs||data.data?.jobs:Array.isArray(data)?data:path(data,s.configJson?.itemsPath||"jobs")||data.results;if(!Array.isArray(c))throw Error("parse_error: adapter response has no job array");return c}
function rows(data,s){return collection(data,s).map(x=>job({...x,externalId:x.jobReqId||x.requisitionId||x.id||x.jobId,title:x.title||x.jobTitle||x.name,company:x.company||x.companyName,location:x.location||x.locations?.[0]?.city,url:x.applyUrl||x.externalPath||x.url,description:x.description||x.jobDescription,postedAt:x.postedDate||x.postedAt},s)).filter(j=>j.title)}
async function xpathPage(html,url,s,cfg){const[{DOMParser},{default:xp}]=await Promise.all([import("@xmldom/xmldom"),import("xpath")]),doc=new DOMParser().parseFromString(html,"application/xml"),value=(node,expr)=>{if(!expr)return"";const found=xp.select1(expr,node);return typeof found==="string"?found.trim():String(found?.value??found?.textContent??"").trim()},nodes=xp.select(cfg.itemXPath,doc);if(!Array.isArray(nodes)||!nodes.length)throw Error("selector_broken: XPath item mapping returned no nodes");const jobs=nodes.map(n=>job({title:value(n,cfg.titleXPath||".//h1|.//h2|.//h3|.//a"),company:value(n,cfg.companyXPath),location:value(n,cfg.locationXPath),url:value(n,cfg.urlXPath||".//a/@href"),descriptionText:value(n,cfg.descriptionXPath)},s)).filter(j=>j.title),next=value(doc,cfg.nextXPath);return{jobs,next:next?new URL(next,url).toString():null}}
async function page(url,s){const r=await get(url,s),cfg=s.configJson||{};if(r.type.includes("json")||["json","workday","eightfold","icims","talentbrew-jibe","phenom"].includes(s.adapterId)||cfg.mode==="json")return{jobs:rows(JSON.parse(r.text),s),next:null};if(r.type.includes("xml")||cfg.mode==="rss"){const{XMLParser}=await import("fast-xml-parser"),x=new XMLParser({ignoreAttributes:false}).parse(r.text),items=x?.rss?.channel?.item||x?.feed?.entry||[];return{jobs:(Array.isArray(items)?items:[items]).map(i=>job({title:i.title,company:s.name,url:typeof i.link==="string"?i.link:i.link?.["@_href"],description:i.description||i.summary,postedAt:i.pubDate||i.updated,externalId:i.guid?.["#text"]||i.guid||i.id},s)),next:null}}if(cfg.itemXPath)return xpathPage(r.text,url,s,cfg);const{load}=await import("cheerio"),$=load(r.text),pick=(n,sel)=>{if(!sel)return"";const f=$(n).is(sel)?$(n):$(n).find(sel).first();return(f.attr("href")||f.text()).trim()},scope=cfg.itemSelector||"[data-job-id], .job, .job-item, li",jobs=$(scope).toArray().map(n=>job({title:pick(n,cfg.titleSelector||"h1,h2,h3,a"),company:pick(n,cfg.companySelector),location:pick(n,cfg.locationSelector),url:pick(n,cfg.urlSelector||"a[href]"),descriptionText:pick(n,cfg.descriptionSelector)},s)).filter(j=>j.title),next=cfg.nextSelector?$(cfg.nextSelector).first().attr("href"):null;return{jobs,next:next?new URL(next,url).toString():null}}
async function requestHeaders(s){const cfg=s.configJson||{},headers={...(cfg.requestHeaders||{})};let cookies=Array.isArray(cfg.sessionCookies)?cfg.sessionCookies:[];if(s.sessionStatePath)try{const state=JSON.parse(await readFile(s.sessionStatePath,"utf8"));cookies=[...cookies,...(state.cookies||[])]}catch{throw Error("auth_required: saved browser session is unreadable")};if(cookies.length)headers.cookie=cookies.map(c=>typeof c==="string"?c:`${c.name}=${c.value}`).join("; ");return headers}
async function platformDirect(s){await robots(s);const cfg=s.configJson||{},max=cfg.maxPages||50;let state={},out=[],pages=0,complete=true;s.__requestHeaders=await requestHeaders(s);while(pages<max){const request=requestFor(s.adapterId,s.baseUrl,{...cfg,...state}),response=await get(request.url,s,0,request),data=JSON.parse(response.text),items=collection(data,s);for(const item of items){let full=item,detail=item[cfg.detailUrlField||"detailUrl"];if(detail){const detailResponse=await get(new URL(detail,response.url).toString(),s);const detailData=JSON.parse(detailResponse.text);full={...item,...detailData}}const normalized=job({...full,externalId:full.jobReqId||full.requisitionId||full.id||full.jobId,title:full.title||full.jobTitle||full.name,company:full.company||full.companyName,location:full.location||full.locations?.[0]?.city,url:full.applyUrl||full.externalPath||full.url,description:full.description||full.jobDescription,postedAt:full.postedDate||full.postedAt},s);if(normalized.title)out.push(normalized)}pages++;state=request.next(data);if(!state)break}if(state)complete=false;return{jobs:out,complete,pages,mode:"direct-platform"}}
async function direct(s){if(["workday","eightfold","icims","talentbrew-jibe","phenom"].includes(s.adapterId))return platformDirect(s);await robots(s);const c=s.configJson||{};let u=urlFor(s),out=[],pages=0,complete=true;while(u&&pages<(c.maxPages||50)){const x=await page(u,s);out.push(...x.jobs);pages++;if(c.pageParam){const n=new URL(urlFor(s));n.searchParams.set(c.pageParam,String(pages+(c.pageStart||0)));u=pages<(c.maxPages||50)&&x.jobs.length?n.toString():null}else u=x.next}if(u)complete=false;return{jobs:out,complete,pages,mode:"direct"}}
const pauses=new Map;const waitForUser=runId=>new Promise((resolve,reject)=>pauses.set(runId,{resolve,reject}));
export async function installNavigationGuard(page,s){await page.route("**/*",async route=>{const request=route.request();const guarded=["document","frame"].includes(request.resourceType())||request.isNavigationRequest();if(!guarded)return route.continue();try{await allowed(request.url(),s);await route.continue()}catch{await route.abort("blockedbyclient")}});page.on("popup",popup=>installNavigationGuard(popup,s).catch(()=>popup.close().catch(()=>{})))}
async function browser(s,capture){const exe=edge.find(existsSync);if(!exe)throw Error("browser_incompatible: Microsoft Edge was not found");const{chromium}=await import("playwright-core"),b=await chromium.launch({executablePath:exe,headless:s.headless!==false});try{const ctx=await b.newContext(s.sessionStatePath?{storageState:s.sessionStatePath}:{}),p=await ctx.newPage();await installNavigationGuard(p,s);await p.goto((await allowed(urlFor(s),s)).toString(),{waitUntil:"domcontentloaded",timeout:30000});cancelledError(s.__runId);if(s.headless===false){emit("needs_user_action",s.__runId,{kind:capture?"login_capture":"login_or_captcha",message:"Complete login or CAPTCHA in Edge, then choose Resume."});await waitForUser(s.__runId);cancelledError(s.__runId)}if(capture){emit("completed",s.__runId,{complete:true,capturedStorageStateBase64:Buffer.from(JSON.stringify(await ctx.storageState())).toString("base64")});return{jobs:[],complete:true,pages:1}}const x=await p.evaluate(()=>[...document.querySelectorAll("[data-job-id], .job, .job-item")].map(n=>({title:n.querySelector("h1,h2,h3,a")?.textContent?.trim(),url:n.querySelector("a")?.href,descriptionText:n.textContent?.trim()})));return{jobs:x.map(i=>job(i,s)),complete:true,pages:1}}finally{pauses.delete(s.__runId);await b.close()}}
async function scrape(s){try{return await direct(s)}catch(error){const declared=adapters[s.adapterId]?.capabilities.includes("playwright-fallback");if(s.configJson?.allowPlaywrightFallback&&declared&&/^(parse_error|selector_broken)/.test(String(error.message||error))){emit("warning",s.__runId,{code:"playwright_fallback",message:"Declared direct adapter fallback started after parse failure."});return{...(await browser(s,false)),mode:"playwright-fallback"}}throw error}}
async function run(q){const started=Date.now(),s={...(q.source||{}),__runId:q.runId},a=adapters[s.adapterId],cfg=s.configJson||{},required=s.adapterId==="static-css"?["itemSelector","titleSelector"]:s.adapterId==="static-xpath"?["itemXPath","titleXPath"]:s.adapterId==="json"?["itemsPath"]:[],warnings=required.filter(key=>!cfg[key]).map(key=>`Missing recommended field: ${key}`);emit("started",q.runId,{command:q.command,adapter:s.adapterId,adapterVersion:a?.version||null,protocolVersion:V});if(!a||a.unsupported||s.kind==="reference")throw Error(s.adapterId==="reference"?"incomplete: reference source cannot be scraped":"incomplete: source needs a verified custom adapter; it remains disabled");if(q.command==="probe_source"){emit("completed",q.runId,{recommendedAdapter:s.adapterId,adapterVersion:a.version,requiredFields:required,warnings,mode:cfg.mode||"direct",timingMs:Date.now()-started,complete:true});return}if(q.command==="cancel"){emit("cancelled",q.runId,{complete:false});return}const o=q.command==="capture_session"?await browser(s,true):(cfg.mode==="playwright"||s.adapterId==="playwright"?await browser(s,false):await scrape(s)),jobs=q.command==="test_source"?o.jobs.slice(0,10):o.jobs;for(let i=0;i<jobs.length;i++){emit("progress",q.runId,{current:i+1,total:jobs.length,pages:o.pages});emit("job",q.runId,jobs[i])}emit("completed",q.runId,{complete:o.complete,discovered:o.jobs.length,persisted:q.command==="test_source"?0:jobs.length,mode:o.mode||cfg.mode||"direct",warnings,timingMs:Date.now()-started,pages:o.pages})}
const code=e=>/^(auth_required|captcha_required|robots_denied|rate_limited|browser_incompatible|selector_broken|parse_error|network_error|incomplete|cancelled)/.exec(String(e?.message||e))?.[1]||"parse_error";
const receive=line=>{try{const q=JSON.parse(line);if(q.protocolVersion!==V)throw Error("Unsupported protocol version");if(q.command==="resume"){const pause=pauses.get(q.runId);if(!pause)throw Error("incomplete: no paused scrape");pause.resolve();return}if(q.command==="cancel"){cancelled.add(q.runId);const pause=pauses.get(q.runId);if(pause)pause.reject(Error("cancelled"));return}if(!["probe_source","test_source","scrape_source","capture_session"].includes(q.command))throw Error("Unknown command");cancelled.delete(q.runId);run(q).then(()=>cancelled.delete(q.runId)).catch(e=>{cancelled.delete(q.runId);const failure=code(e);emit(failure==="cancelled"?"cancelled":"failed",q.runId,{code:failure,message:String(e.message||e),complete:false,needsUserAction:["auth_required","captcha_required"].includes(failure)})})}catch(e){emit("failed",q.runId||"unknown",{code:"parse_error",message:String(e.message||e),complete:false})}};
if(process.argv[1]?.replace(/\\/g,"/").endsWith("/worker.mjs"))readline.createInterface({input:process.stdin,crlfDelay:Infinity}).on("line",receive);
